#!/bin/sh

echo 'name: HTTP
version: 3001.0.2
license: BSD3
copyright: Copyright (c) 2002, Warrick Gray
           Copyright (c) 2002-2005, Ian Lynagh
           Copyright (c) 2003-2006, Bjorn Bringert
           Copyright (c) 2004, Andre Furtado
           Copyright (c) 2004, Ganesh Sittampalam
           Copyright (c) 2004-2005, Dominic Steinitz
maintainer: Bjorn Bringert <bjorn@bringert.net>
stability:
homepage: http://www.haskell.org/http/
package-url:
description: A library for client-side HTTP
category:
author: Warrick Gray <warrick.gray@hotmail.com>
exposed: True
exposed-modules: Network.Stream Network.TCP Network.HTTP
                 Network.Browser
hidden-modules: Network.HTTP.Base64 Network.HTTP.MD5
                Network.HTTP.MD5Aux
import-dirs: /usr/lib/ghc-6.8.1/lib/HTTP-3001.0.2
library-dirs: /usr/lib/ghc-6.8.1/lib/HTTP-3001.0.2
hs-libraries: HSHTTP-3001.0.2
extra-libraries:
extra-ghci-libraries:
include-dirs:
includes:
depends: base-3.0.0.0 array-0.1.0.0 network-2.1.0.0 parsec-2.1.0.0
hugs-options:
cc-options:
ld-options:
framework-dirs:
frameworks:
haddock-interfaces: /usr/share/doc/HTTP-3001.0.2/html/HTTP.haddock
haddock-html: /usr/share/doc/HTTP-3001.0.2/html' | /usr/bin/ghc-pkg update -
